
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


CREATE ROLE RL_SIACORE;


GRANT
    CONNECT,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    DROP ANY TABLE,
    DROP ANY VIEW,
    DROP ANY PROCEDURE
TO RL_SIACORE;


SELECT * FROM DBA_ROLES WHERE ROLE = 'RL_SIACORE';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_SIACORE';