CREATE USER SIACORE IDENTIFIED BY "123"
    DEFAULT TABLESPACE TS_SIA
    TEMPORARY TABLESPACE TS_SIA_TEMP
    PROFILE PF_SIACORE
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;

GRANT CREATE SESSION TO SIACORE;
GRANT CREATE TABLE, CREATE VIEW, DROP ANY TABLE, DROP ANY VIEW TO SIACORE;


DROP USER SIACORE;